
# --- Base de datos MySQL ---
db.url=jdbc:mysql://localhost:3306/sesionbdservletcalif?useSSL=false&serverTimezone=America/Mexico_City
db.usuario=root
db.password=

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls=true
mail.remitente=gutirrresisai@gmail.com
mail.password=fykf kmqc desa upby
